:PROPERTIES:
:ID:       ba64e6db-38ee-45bf-bcb7-2771419d232a
:END:
#+title: Phoenix Albatross: Text for Ikeda

Iannis Xenakis' orchestral work Duel (1959) is a "game for 56 musicians divided into two orchestras with two conductors" based on he Mahematical Theory of Game play.[^1] The players of the game are two conductors, and the orchestras play "tactics," chosen by the conductors. Tactics correspond to individual cards in a card game. In the score of the piece, tactics correspond to score sections which have clearly distinguisheable sonic characteristics.  Xenakis describes the characteristics as follows:

1. Event I: A cluster of sonic grains such as pizzicati, blows with the wooden part of the bow, and very brief arco sounds distributed stochastically.
2. Event II: Parallel Sustained strings with fluctuations.
3. Event III: Networks of intertwined string glissandi
4. Event IV: Stochastic percussion sounds
5. Even V: Stochastic wind instrument sounds
6. Event VI: Silence

The two conductors take turn choosing tactics, like playing cards, to achieve a high score. The orchestral music is generated as a byproduct of the game. So, its performance is intended to realize the game, not music. In his "Formalized Music," Xenakis called music controlled by other elements "Heteronomous music" that have nothing to do with music, and resembles more an experiment in Game Theory. In Xenakis' terminology, this is called "Autonomous Music" or "La musique pour la musique".

The tactics are not randomly selected. The process of competition by the conductors automatically limits the tactics that conductors can choose. The limitation of possibility causes certain tendencies in the music that is generated. Xenakis examined the desirability of sound combinations in creating game rules, defined as a payoff (game) matrix. Therefore, the execution of the game automatically generates music that he generally finds favorable. Also, different music is generated each time the game is played. In Ikeda's view, this is a humanized version of algorithmic composition usually realized by computers.

Xenakis' Game theory works, Duel, Stratégie (1962), and Linaia-Agon (1972), are rarely performed due to their extreme technical complexity to prepare and to perform. Linaia-Agon, in particular, requires the performers to choose their own tactics while playing an extremely difficult score, forcing them to decide what to play in advance, which is a realistic approach. Ikeda believes that the lack of these performance opportunities has led to a lack of validation of the game itself. The Duel rules themselves can easily be written in a programming language. Running it as a simulation or game program, rather than with an orchestra or musical score, would allow refining Xenakis' idea of the musical game he envisioned. After receiving a proposal from Professor Iannis Zannos for a remote performance based on Duel, Ikeda created a version of the game matrix described by Xenakis in Formalized Music.  After running several simulations of games on a computer he discovered that the rules these matrices do not result in a fair game, but are biased to let the first player win more often than the second player.  Xenakis also mentions this property and the need to create a fair game. In the quest to create such a fair game, Ikeda n created a new game matrix, which was first performed live by two improvisers and Ikeda's own referee. He then created a game program using Supercollider and performed a duo performance with Zannos, which is presented here in the piece "Phoenix Albatross".  In this performance, there is no referee.  Instead, the two performers, Ikeda and Zannos are responsible for choosing the best move by consulting the points written on the game matrix.  Ikeda created an graphic display of that matrix which both players consult at each move.  We call the two players x (Phoenix) and y (Albatross).  Player x chooses moves from the columns of the matrix and player y chooses moves from the rows of the matrix. At each move, the matrix display updates to show which row or column has been chosen by the move of the last player.  The other player has the responsibility to choose from that row or column one cell which maximises the possibilities of winning the game.  Player x must choose the smallest values from a column, and player y must choose the greatest value from a row.  [これをcheck してください。If necessary please exchange x and y and / or column/row in the above sentence!].

It would be very easy to create a function that chooses the best move for each player and suggests it or plays it automatically.  However, we decided on purpose to leave this task to the players themselves.  This heightened the demand for concentration and created a real sense of suspense which is part of the human and mucsical aspect of the performance.
