:PROPERTIES:
:ID:       0a7931a2-30e2-4b07-8f16-9a41827b1326
:END:
#+title: Phoenix Albatross: Intro Text for Zannos

In this paper we present an attempt to reinterpret aspects of Xenakis' work in the context of 21st century performance practice using live-coding and embodied performance or dance with sensors.  Xenakis worked at a time when live interaction with computers was just starting.  He worked mostly with non-interacive computer systems, but at the same time he launched the visionary project UPIC to develop technology that enabled interactive sound design.  Thus, we view creating interactive works based on Xenaki's vision as a natural and necessary continuation of his legacy.  In fact, the present project takes a radical stance toward this idea.  It engages at the same time with three current challenging aspects in the field of contemporary computer music and performance.  These are:

1. Live coding: Executing code during the performance in order to generate the event sequences and the sound generating processes that produce the music.
2. Linking human body movement to sound generation ("embodied performance").  In our case, dancers use sensors to influence the parameters of the sound generating processes and thus to fundamentally modify the qualities of the sound during the performance.  Dancers become almost like instrumentalists interpreting the piece, with one important difference: They in fact enter in dialogue with the live coders, by modifying what they specify with their code in real time
3. Enabling distributed mode of performance worldwide through the internet: Performers play the piece in different venues in different locations at the same time, sharing control data and code over the internet to communicate and create one distributed performance.

The work which is presented here is based on the part of Xenakis's work which is by far less performed than any other. These are three works based on Game Theory, (Duel, Stratégie and Linaea-Agon) which incorporate a live simulation of a game within the performance itsalf.  As a result, these works are extremely difficult to perform instrumentally on stage, because they involve making of live choices by the performers, based on complex game rules.  On the other hand, such a setting is naturally more suitable for performance in a setting involving computers in real time.  Computers could in fact perform a simulation of the game in real time without the intervention of humans, as is often done in game simulations for both peaceful and non-peaceful conflict scenarios.  In our piece, we re-introduce the human performance factor by relying on the performers to make the choices based on live calculations and spontaneous choice, using the computer to track the score and to provide visual cues about the state of the game.

In his introduction to the chapter on Musical Strategy, Xenakis describes the idea of Heteronomous Music, as a way to introduce a concept of external conflict between opposing orchestras or instrumentalists.  The sonic discourse which arises in this setting is seen by Xenakis as "a very strict, although ofen stochastic, succession of sets of acts of sonic opposition".  We regard this setting as fundamental aspect of the aesthetic and musical goals of the works discussed here.  Xenakis explains that this kind of heteronomy is present in traditional musical forms as for example in Indian Classical Music, where two intstrumentalists engage in playful competitive musical dialogue.  In fact, there are also references to this genre in classical western music, in the genre of "Bataglia" mainly in the 17th and 18h century. An prominent example inspired by this genre is the work by Claudio Monteverdi "Il Combattimento di Tancredi e Clodinda" (1624), based on Canto 12 from Torquato Tasso's "Gerusalemme Liberata".  In a way, Xenakis work in this field coincides with major events in Geopolitics on the one hand and with budding developments in computer and telecommunications technology on the other.   In Geopolitics, the Cold War conflict between the USA and the Soviet Union was a decisive factor in the development of Game Theory. The biography of Nobel Prize winner John Nash is a dramatic example of this.  Another characteristic event in this context is the Cuba missile crisis of 1962, which happened in the same year as the composition of Stratégie by Iannis Xenakis.  In computer technology, the development of computer games concides with the birth of interactivity in computing and has become a driving factor in the field.  Computer games are now interlinked with development of Virtual Reality and so-called Virtual Worlds such as the Metaverse.  Our work approaches the potential of this field from the grass-roots or rhizomatic perspective of open-source and DIY (Do It Yourself).  In this way we want to point out an alternative playful and creative approach to technology, that emphasizes empowerment of the artist and independence from large multinational Gaming, Social Media and Virtual Reality corporations.  In parallel, we are aware of other performance forms that employ the battle-paradigm in popular culture, such as dance battles, as well as the hacking marathons of the "Demoscene" subculture, which open alternative creative approaches to mainstream gaming technology.

The background for this project is provided by a telematic dance project started by Iannis Zannos in 2018 as part of a sabbatical residency at the University of Arts of Tokyo, which resulted in a series of collaborations with Japanese dancers and composers. The online live coding framework that enabled the collaboration was developed by Zannos with the help of senior undergraduate students and of post-doctoral students at the Department of Audiovisual Arts of the Ionian university, where he works. This framework does not rely on streaming audio over the network.  Instead, only program code and sensor data are streamed over the network, using the UDP-based protocol Open Sound Control (OSC).  The sound is then synhesized on SuperCollider locally at each venue.  In other words one may say that the score as well as the movements of the interpreters are broadcast over the network, and the instruments that render this score are the computers at each venue.  This method requires the minimum amount of data to be sent over the network and is therefore very fast. The delay between coders and dancers at each location and the reaction of the computers at remote locations is very small, as small as a fast internet connection permits (usually less than 1/5 or 1/10 of a second between Greece and Japan).

In 2021, Zannos approached the composer Takumi Ikeda who is an experienced SuperCollider programmer and performer, and proposed a collaboration along these lines.  The collaboration gradually developed into the present project in the course of several online as well as face-to-face meetings. Ikeda became quickly familiar with this framework and contributed sound processing algorithms that formed the main skeleton for the present piece and performances.  Starting early in 2022, we rehearsed these algorithms in live-coding sessions with dancers in Greece, with Ikeda joining us remotely live-coding over the network.  In parallel, we worked on models of the game described by Xenakis in chaper 4 of Formalized music, which were implemented mainly by Ikeda. In early September of 2022 we performed a first full version of the piece in Tokyo, while the greek dancer Tasos Pappas-Petrides joined us from Athens over the network.  We present this session in video at the end of the present talk.

The presentation is now continued by Mr. Ikeda who will introduce the details of Xenakis' approach to Game Theory and describe his work for the realization of the present work.
